services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Wacon\Easyshop\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Wacon\Easyshop\Service\PaymentGateway\PayPalService:
    public: true
